from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_10/models/cashbotHQ/ZONE17a',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 10002: {'type': 'gagBarrel',
         'name': 'gag',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-1.80931818485, 65.0541229248, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 0},
 10007: {'type': 'nodepath',
         'name': 'props',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': 1},
 10008: {'type': 'boardOfficeShelf',
         'name': 'frontShelf',
         'comment': '',
         'parentEntId': 10007,
         'pos': Point3(0.75479054451, -116.741004944, 0.0),
         'hpr': Vec3(180.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'mintId': 12500},
 10009: {'type': 'boardOfficeShelf',
         'name': 'backShelf1',
         'comment': '',
         'parentEntId': 10007,
         'pos': Point3(5.09813165665, 63.6601753235, 0.0),
         'hpr': Vec3(270.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'mintId': 12500},
 10010: {'type': 'boardOfficeShelf',
         'name': 'copy of backShelf1',
         'comment': '',
         'parentEntId': 10007,
         'pos': Point3(-3.80197167397, 81.7602081299, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'mintId': 12500},
 20000: {'type': 'nodepath',
         'name': 'stompers',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0.75, 0, 0.5),
         'hpr': Vec3(0, 0, 0),
         'scale': 1},
 20001: {'type': 'stomper',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(0, 0, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 5,
         'headScale': Point3(7, 5, 7),
         'modelPath': 0,
         'motion': 3,
         'period': 4.0,
         'phaseShift': 0.0,
         'range': 30.0,
         'shaftScale': Point3(0.5, 12, 0.5),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20002: {'type': 'stomper',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(0, -14.3294, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 5,
         'headScale': Point3(7, 5, 7),
         'modelPath': 0,
         'motion': 3,
         'period': 2.0,
         'phaseShift': 0.0,
         'range': 10.0,
         'shaftScale': Point3(0.5, 12, 0.5),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20003: {'type': 'stomper',
         'name': 'copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(0, -28.3252, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 5,
         'headScale': Point3(7, 5, 7),
         'modelPath': 0,
         'motion': 4,
         'period': 2.0,
         'phaseShift': 0.5,
         'range': 10.0,
         'shaftScale': Point3(0.5, 12, 0.5),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 2,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20004: {'type': 'stomper',
         'name': 'copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(-3.5, 16.2588, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 5,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 1,
         'period': 3.0001373423482587,
         'phaseShift': 0.0,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20005: {'type': 'stomper',
         'name': 'copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(3.5, 16.2588, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 5,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 0,
         'period': 1.5,
         'phaseShift': 0.0,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 1,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20006: {'type': 'stomper',
         'name': 'copy of copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(-3.5, 23.4392, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 5,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 2,
         'period': 1.5,
         'phaseShift': 0.5,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0},
 20007: {'type': 'stomper',
         'name': 'copy of copy of copy of copy of <unnamed>',
         'comment': '',
         'parentEntId': 20000,
         'pos': Point3(3.5, 23.4392, 0),
         'hpr': Point3(0, 0, 0),
         'scale': 1,
         'crushCellId': None,
         'damage': 5,
         'headScale': Point3(3.5, 5, 3.5),
         'modelPath': 0,
         'motion': 3,
         'period': 5.0,
         'phaseShift': 0.5,
         'range': 15.0,
         'shaftScale': Point3(0.71, 12, 0.71),
         'soundLen': 0,
         'soundOn': 1,
         'soundPath': 0,
         'style': 'vertical',
         'switchId': 0,
         'wantShadow': 1,
         'wantSmoke': 1,
         'zOffset': 0}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
