from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_10/models/cashbotHQ/ZONE69a',
        'wantDoors': 1},
 1001: {'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 10000: {'type': 'nodepath',
         'name': 'cogs',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-2.0, 0.0, 0.0),
         'hpr': Vec3(180.0, 0.0, 0.0),
         'scale': 1},
 10170: {'type': 'nodepath',
         'name': 'barrels',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(24.661, 0.057, 0.025),
         'hpr': Vec3(270.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0)},
 10169: {'type': 'gagBarrel',
         'name': 'gag',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(0.0, 0.0, 0.0),
         'hpr': Vec3(1.0, 0.0, 0.0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10171: {'type': 'gagBarrel',
         'name': 'gagLeft',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(-3.0, 0.0, 0.0),
         'hpr': Vec3(-6.0, 0.0, 0.0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10172: {'type': 'gagBarrel',
         'name': 'gagRight',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(3.0, 0.0, 0.0),
         'hpr': Vec3(9.0, 0.0, 0.0),
         'scale': 1,
         'gagLevel': 5,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10177: {'type': 'healBarrel',
         'name': 'healLeft',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(-1.05319225788, 0.0, 4.12134313583),
         'hpr': Vec3(20.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6},
 10178: {'type': 'healBarrel',
         'name': 'healRight',
         'comment': '',
         'parentEntId': 10170,
         'pos': Point3(2.16605138779, 0.0, 4.12134313583),
         'hpr': Vec3(0.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'rewardPerGrab': 5,
         'rewardPerGrabMax': 6}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
