from SpecImports import *
import random
from toontown.toonbase import ToontownGlobals
CogParent = 10000
CogParent1 = 11000
BattlePlace1 = 10000
BattlePlace2 = 11000
BattleCellId = 0
Battle2CellId = 1
BattleCells = {BattleCellId: {'parentEntId': BattlePlace1,
                'pos': Point3(0, 0, 0)},
 Battle2CellId: {'parentEntId': BattlePlace2,
                     'pos': Point3(0, 0, 0)}}
			
				
CogData = [{'parentEntId': CogParent1,
  'boss': 0,
  'level': random.choice([5, 6, 7, 8]),
  'battleCell': Battle2CellId,
  'pos': Point3(-8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': random.choice([5, 6, 7, 8]),
  'battleCell': Battle2CellId,
  'pos': Point3(-3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': random.choice([5, 6, 7, 8]),
  'battleCell': Battle2CellId,
  'pos': Point3(3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent1,
  'boss': 0,
  'level': random.choice([5, 6, 7, 8]),
  'battleCell': Battle2CellId,
  'pos': Point3(8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
{'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice([9, 10, 11]),
  'battleCell': BattleCellId,
  'pos': Point3(-8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice([9, 10, 11]),
  'battleCell': BattleCellId,
  'pos': Point3(-3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice([9, 10, 11]),
  'battleCell': BattleCellId,
  'pos': Point3(3, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1},
 {'parentEntId': CogParent,
  'boss': 0,
  'level': random.choice([9, 10, 11]),
  'battleCell': BattleCellId,
  'pos': Point3(8, 4, 0),
  'h': 180,
  'behavior': 'stand',
  'path': None,
  'skeleton': 1}]
ReserveCogData = []
