from otp.speedchat.SCObject import SCObject
from otp.speedchat.SCMenu import SCMenu
from otp.speedchat.SCElement import SCElement
from otp.speedchat.SCMenuHolder import SCMenuHolder
from otp.speedchat.SCTerminal import SCTerminal
from otp.speedchat.SCCustomMenu import SCCustomMenu
from otp.speedchat.SCEmoteMenu import SCEmoteMenu
from otp.speedchat.SCStaticTextTerminal import SCStaticTextTerminal
from otp.speedchat.SCGMTextTerminal import SCGMTextTerminal
from otp.speedchat.SCCustomTerminal import SCCustomTerminal
from otp.speedchat.SCEmoteTerminal import SCEmoteTerminal
from otp.speedchat.SCColorScheme import SCColorScheme