from toontown.speedchat.TTSCToontaskMenu import TTSCToontaskMenu
from toontown.speedchat.TTSCFactoryMenu import TTSCFactoryMenu
from toontown.speedchat.TTSCCogMenu import TTSCCogMenu

if hasattr(base, 'wantPets') and base.wantPets:
    from toontown.speedchat.TTSCPetTrickMenu import TTSCPetTrickMenu

from toontown.speedchat.TTSCPromotionalMenu import TTSCPromotionalMenu
from toontown.speedchat.TTSCToontaskTerminal import TTSCToontaskTerminal
from toontown.speedchat.TTSCResistanceMenu import TTSCResistanceMenu
from toontown.speedchat.TTSCResistanceTerminal import TTSCResistanceTerminal
from toontown.speedchat.TTSCKartRacingMenu import TTSCKartRacingMenu
from toontown.speedchat.TTSCGolfMenu import TTSCGolfMenu
from toontown.speedchat.TTSCBoardingMenu import TTSCBoardingMenu
from toontown.speedchat.TTSCSingingMenu import TTSCSingingMenu
from toontown.speedchat.TTSCAprilToonsMenu import TTSCAprilToonsMenu
from toontown.speedchat.TTSCSillyPhaseOneMenu import TTSCSillyPhaseOneMenu
from toontown.speedchat.TTSCSillyPhaseTwoMenu import TTSCSillyPhaseTwoMenu
from toontown.speedchat.TTSCSillyPhaseThreeMenu import TTSCSillyPhaseThreeMenu
from toontown.speedchat.TTSCSillyPhaseFourMenu import TTSCSillyPhaseFourMenu
from toontown.speedchat.TTSCSillyPhaseFiveMenu import TTSCSillyPhaseFiveMenu
from toontown.speedchat.TTSCVictoryPartiesMenu import TTSCVictoryPartiesMenu
from toontown.speedchat.TTSCSellbotNerfMenu import TTSCSellbotNerfMenu
from toontown.speedchat.TTSCJellybeanJamMenu import TTSCJellybeanJamMenu
from toontown.speedchat.TTSCHalloweenMenu import TTSCHalloweenMenu
from toontown.speedchat.TTSCWinterMenu import TTSCWinterMenu
from toontown.speedchat.TTSCSellbotInvasionMenu import TTSCSellbotInvasionMenu
from toontown.speedchat.TTSCSellbotFieldOfficeMenu import TTSCSellbotFieldOfficeMenu
from toontown.speedchat.TTSCIdesOfMarchMenu import TTSCIdesOfMarchMenu
