BLACKLIST = [
    'null',
    'kill yourself',
    'fist me daddy',
    "don't flex",
    'go die',
    'fuck',
    'fucker',
    'dick',
    'dickwad',
    'asshole',
    'asswipe',
    'cum',
    'cumming',
    'cumwad',
    'nigga',
    'niggas',
    'nigger',
    'niggers',
    'dan kk',
    'dan k',
    'k k k',
    'kk k',
    'k kk',
    'harder daddy',
    'harder dad',
]