BLACKLIST = [
    'null',
    'kill yourself',
    'fist me daddy',
    "don't flex",
    'go die',
    'fuck',
    'fucker',
    'dick',
    'dickwad',
    'asshole',
    'asswipe',
    'cum',
    'cumming',
    'cumwad',
    'nigga',
    'niggas',
    'nigger',
    'niggers',
    'dan kk',
    'dan k',
    'k k k',
    'kk k',
    'k kk',
    'harder daddy',
    'harder dad',
    'shh :i tt',
    'sf u k k',
    'sf u kk',
    'sf u cee k',
    'sf u k',
    'sf u cee k k',
    'sf u cee kk',
    'org y',
    'org as mm',
    'kill your self',
    "kill you're self",
    're tart',
    're tart ed',
    're 1 tart',
    're 1 tart ed',
    'sh it',
    'shh it',
    'sh 1 it,'
    'shh 1 it',
    'hit lure',
    'hit 1 lure',
    "'n i gg err",
    "'n i gg er",
    "'n i gg eh r",
    "gg ay",
    "gg 1 ay",
    ":d icky",
    ":d 1 icky",
    "dd 1 icky",
    "dd icky",
    ":d sick",
    ":d 1 sick",
    "dd sick",
    "dd 1 sick",
    ";d icky",
    ";d 1 icky",
    "xd 1 icky",
    "xd icky",
    ";d sick",
    ";d 1 sick",
    "xd sick",
    "xd 1 sick",
]