BLACKLIST = [
    'null',
    'kill yourself',
    'fist me daddy',
    "don't flex",
    'go die',
    'fuck',
    'fucker',
    'dick',
    'dickwad',
    'asshole',
    'asswipe',
    'cum',
    'cumming',
    'cumwad',
    'nigga',
    'niggas',
    'nigger',
    'niggers',
]